% Originally this was at the end of noise


myFigName = 'test_ch2/test_2_2_pointCloud';
%============PLOT==============
plot(t,real(N), 'r', t, data, 'g' ); hold on;
annotation(gcf,'textbox',[0.5 0.6 0.1 0.1],'String',...
    [' numOsurfs = ' num2str(numOsurfs)...
    '\newline  TotPhotons = ' num2str(TotPhotons2)...
    '\newline  TotPhotons\_noise = ' num2str(TotPhotons_noise2)...
    '\newline SNR = ' num2str(SNR)],...
    'FontSize',12,'EdgeColor','red', 'HorizontalAlignment','Center',...
    'BackgroundColor',[.7 .9 .7], 'Interpreter', 'tex'); %
saveas(gcf,['../../images/' myFigName],'eps2');
saveas(gcf,['../../images/' myFigName],'fig');
toc